/*
 * This file is generated by jOOQ.
 */
package com.shop.jooq.db.public_;


import com.shop.jooq.db.public_.tables.Item;
import com.shop.jooq.db.public_.tables.Order;
import com.shop.jooq.db.public_.tables.OrderItem;
import com.shop.jooq.db.public_.tables.User;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.item</code>.
     */
    public static final Item ITEM = Item.ITEM;

    /**
     * The table <code>public.order</code>.
     */
    public static final Order ORDER = Order.ORDER;

    /**
     * The table <code>public.order_item</code>.
     */
    public static final OrderItem ORDER_ITEM = OrderItem.ORDER_ITEM;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;
}
