/*
 * This file is generated by jOOQ.
 */
package com.shop.jooq.db.pg_catalog.tables;


import com.shop.jooq.db.pg_catalog.Keys;
import com.shop.jooq.db.pg_catalog.PgCatalog;
import com.shop.jooq.db.pg_catalog.tables.records.PgPublicationNamespaceRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgPublicationNamespace extends TableImpl<PgPublicationNamespaceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>pg_catalog.pg_publication_namespace</code>
     */
    public static final PgPublicationNamespace PG_PUBLICATION_NAMESPACE = new PgPublicationNamespace();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PgPublicationNamespaceRecord> getRecordType() {
        return PgPublicationNamespaceRecord.class;
    }

    /**
     * The column <code>pg_catalog.pg_publication_namespace.oid</code>.
     */
    public final TableField<PgPublicationNamespaceRecord, Long> OID = createField(DSL.name("oid"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_publication_namespace.pnpubid</code>.
     */
    public final TableField<PgPublicationNamespaceRecord, Long> PNPUBID = createField(DSL.name("pnpubid"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_publication_namespace.pnnspid</code>.
     */
    public final TableField<PgPublicationNamespaceRecord, Long> PNNSPID = createField(DSL.name("pnnspid"), SQLDataType.BIGINT.nullable(false), this, "");

    private PgPublicationNamespace(Name alias, Table<PgPublicationNamespaceRecord> aliased) {
        this(alias, aliased, null);
    }

    private PgPublicationNamespace(Name alias, Table<PgPublicationNamespaceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>pg_catalog.pg_publication_namespace</code> table
     * reference
     */
    public PgPublicationNamespace(String alias) {
        this(DSL.name(alias), PG_PUBLICATION_NAMESPACE);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_publication_namespace</code> table
     * reference
     */
    public PgPublicationNamespace(Name alias) {
        this(alias, PG_PUBLICATION_NAMESPACE);
    }

    /**
     * Create a <code>pg_catalog.pg_publication_namespace</code> table reference
     */
    public PgPublicationNamespace() {
        this(DSL.name("pg_publication_namespace"), null);
    }

    public <O extends Record> PgPublicationNamespace(Table<O> child, ForeignKey<O, PgPublicationNamespaceRecord> key) {
        super(child, key, PG_PUBLICATION_NAMESPACE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : PgCatalog.PG_CATALOG;
    }

    @Override
    public UniqueKey<PgPublicationNamespaceRecord> getPrimaryKey() {
        return Keys.PG_PUBLICATION_NAMESPACE_OID_INDEX;
    }

    @Override
    public List<UniqueKey<PgPublicationNamespaceRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.PG_PUBLICATION_NAMESPACE_PNNSPID_PNPUBID_INDEX);
    }

    @Override
    public PgPublicationNamespace as(String alias) {
        return new PgPublicationNamespace(DSL.name(alias), this);
    }

    @Override
    public PgPublicationNamespace as(Name alias) {
        return new PgPublicationNamespace(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PgPublicationNamespace rename(String name) {
        return new PgPublicationNamespace(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PgPublicationNamespace rename(Name name) {
        return new PgPublicationNamespace(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
